version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
